title: Vaibhavi N. Kulkarni
logo: /Downloads/H_shot.png
Hello, I am currently a third-year student at UC Berkeley, studying Applied Mathematics & Statistics.
show_downloads: true
theme: jekyll-theme-minimal
